### PR TITLE
update version

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Review by snoyberg — APPROVED** [review]
These changes look good, thanks! Once CI passes we can merge.

**Comment by getong** [comment]
ubuntu, windows build succcess, only macos fail, but it might be api access too often.

**Comment by snoyberg** [comment]
Given the use case here, I'd be comfortable simplifying the matrix to not include Mac OS, or only including one MacOS build, if that simplifies this PR.

**Comment by getong** [comment]
delete macos in github action, and rebase into one commit.

**Review by snoyberg — APPROVED** [review]

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
